### ISSUE TITLE
how to install this skill in picroft(raspberry pi3) 

### ISSUE THREAD

**Issue by raja434** [Nold360/mycroft_skill-take_picture#1]
how to install this skill in raspberry 3 in piCroft(Mycroft) , please

**Comment by Nold360** [comment]
clone it into your skill directory, f.e. ~/.mycroft/skills or /opt/mycroft/skills.
and than clone the git repository: 
`git clone https://github.com/Nold360/mycroft_skill-take_picture /opt/mycroft/skills/take_picture`

**Comment by raja434** [comment]
thank you a lot
